apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: user:latest
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              port: 8080
              path: /ping
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1