apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: user
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080