apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
  namespace: message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message-container
          image: message:latest
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              port: 8080
              path: /liveness
          ports:
            - containerPort: 8080
        - name: postgres
          image: postgres:16-bookworm
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready --quiet -U $POSTGRES_USER -d postgres"
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: "message"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
        - name: redis
          image: redis:7.4-bookworm
          ports:
            - containerPort: 6379
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1