apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
  namespace: message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message-container
          image: message:latest
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              port: 8080
              path: /ping
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1