apiVersion: v1
kind: Service
metadata:
  name: message-svc
  namespace: message
  labels:
    app: message
spec:
  type: ClusterIP
  selector:
    app: message
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051