env: "local"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 720h
db:
  postgres:
    host: "127.0.0.1"
    port: "5432"
    username: "root"
    ssl_mode: "disable"
    db_name: "auth"
    password: "123456" #used for study only
  redis:
    host: "redis"
    port: "6379"