// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/auth/check_token":{"get":{"produces":["application/json"],"parameters":[{"type":"string","description":"токен на проверку","name":"token","in":"query","required":true}],"responses":{}}},"/auth/ping":{"get":{"produces":["application/json"],"responses":{}}},"/messages":{"get":{"produces":["application/json"],"parameters":[{"type":"string","description":"user id","name":"user_id","in":"query","required":true}],"responses":{}},"post":{"produces":["application/json"],"parameters":[{"description":"сообщение","name":"message","in":"body","required":true,"schema":{"$ref":"#/definitions/http.sendMessageRequest"}}],"responses":{}}},"/messages/ping":{"get":{"produces":["application/json"],"responses":{}}},"/users/ping":{"get":{"produces":["application/json"],"responses":{}}},"/users/{id}":{"get":{"produces":["application/json"],"parameters":[{"type":"string","description":"User ID","name":"id","in":"path","required":true}],"responses":{}}}},"definitions":{"http.sendMessageRequest":{"type":"object","required":["text","user_id"],"properties":{"text":{"type":"string"},"user_id":{"type":"string"}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:80",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
