apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080